import { Platform, StatusBar, StyleSheet } from 'react-native';

export default function getStyles(colors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.surface,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: { flex: 1, backgroundColor: colors.background },
    contentArea: { flex: 1 },
    tabContainer: { flex: 1 },
    scrollContent: { padding: 16, paddingBottom: 40 },

    header: {
      height: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.outlineVariant,
    },
    headerTitle: { fontSize: 22, fontWeight: '600', color: colors.primary },

    readContent: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
    nfcIconPlaceholder: {
      width: 140,
      height: 140,
      borderRadius: 70,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 32,
    },
    descriptionText: {
      fontSize: 16,
      color: colors.onSurfaceVariant,
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 24,
    },

    primaryButton: {
      width: '100%',
      backgroundColor: colors.primary,
      paddingVertical: 16,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
      marginTop: 8,
    },
    primaryButtonText: { color: colors.onPrimary, fontSize: 18, fontWeight: '600' },
    ghostButton: {
      width: '100%',
      paddingVertical: 16,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 12,
    },
    ghostButtonText: { color: colors.onSurfaceVariant, fontSize: 16, fontWeight: '600' },

    statusCard: {
      width: '100%',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      borderRadius: 12,
      padding: 16,
      marginTop: 32,
    },
    statusLabel: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.onSurfaceVariant,
      marginBottom: 4,
    },
    statusValue: { fontSize: 14, fontWeight: '600', color: colors.onSurface },

    optionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
    },
    optionTextContainer: { flex: 1 },
    optionTitle: { fontSize: 17, fontWeight: '600', color: colors.onSurface, marginBottom: 4 },
    optionDesc: { fontSize: 14, color: colors.onSurfaceVariant, lineHeight: 20 },
    chevron: { fontSize: 24, color: colors.primary, paddingLeft: 16 },

    adContainer: {
      minHeight: 124,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceContainerLowest,
      borderTopWidth: 1,
      borderTopColor: colors.outlineVariant,
      paddingTop: 8,
      paddingBottom: 4,
      overflow: 'hidden',
    },
    adLabel: {
      alignSelf: 'flex-start',
      fontSize: 10,
      fontWeight: '700',
      color: colors.onSurfaceVariant,
      letterSpacing: 0.8,
      marginBottom: 8,
      marginLeft: 12,
    },

    inputLabel: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.onSurfaceVariant,
      marginBottom: 8,
      marginTop: 16,
    },
    input: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      borderRadius: 8,
      padding: 16,
      fontSize: 16,
      color: colors.onSurface,
    },

    settingsSection: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
    },
    settingsSectionTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.onSurfaceVariant,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 14,
    },
    settingsRow: { flexDirection: 'row', gap: 10 },
    settingsOption: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      alignItems: 'center',
    },
    settingsOptionSelected: {
      backgroundColor: colors.surfaceVariant,
      borderColor: colors.primary,
    },
    settingsOptionText: { fontSize: 14, fontWeight: '500', color: colors.onSurfaceVariant },
    settingsOptionTextSelected: { color: colors.primary, fontWeight: '700' },
    settingsNote: { fontSize: 12, color: colors.onSurfaceVariant, marginTop: 12, lineHeight: 18 },
    settingsAction: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      borderRadius: 10,
      alignItems: 'center',
    },
    settingsActionText: { fontSize: 14, fontWeight: '600', color: colors.primary },

    bottomNav: {
      flexDirection: 'row',
      backgroundColor: colors.surfaceContainerLowest,
      borderTopWidth: 1,
      borderTopColor: colors.outlineVariant,
      paddingVertical: 8,
      paddingBottom: 16,
    },
    navItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      marginHorizontal: 8,
      borderRadius: 12,
    },
    navItemActive: { backgroundColor: colors.surfaceVariant },
    navIcon: { fontSize: 22, opacity: 0.6 },
    navIconActive: { opacity: 1 },
    navText: { fontSize: 11, fontWeight: '500', color: colors.onSurfaceVariant, marginTop: 4 },
    navTextActive: { color: colors.primary, fontWeight: '700' },
  });
}
